grails-app/domain/periendx/ToDoItem.groovy
package periendx

class ToDoItem {

    String todoItem
    Date creationDate
    Date dueDate
    String status

    static constraints = {
    }
}

grails-app/controllers/periendx/ToDoListController.groovy
package periendx

import grails.converters.JSON

/**
 * Controller to handle TODO List items
 * */
class ToDoListController {

    def toDoItemService

    def index() {
    }

    /**
     * This action invokes a service to fetch to do list
     * */
    def getToDoItems() {
        def data = toDoItemService.getTodoList()
        render data as JSON
    }

    /**
     * This action invokes a service to add new to do item in the list
     * */
    def addTodoItem() {
        def requestJson = request.JSON
        Map loadMap = [:]
        loadMap["dueDate"]= requestJson.dueDate
        loadMap["todoItem"] = requestJson.todoItem

        def data = toDoItemService.addTodoActionItem(loadMap)
        render data as JSON
    }

    /**
     * This action invokes a service to update to do item's status
     * */
    def updateStatus() {
        def id = params.id
        def data = toDoItemService.updateTodoStatus(id)
        render data
    }

    /**
     * This action invokes a service to edit to do item
     * */
    def editTodo() {
        Map updatedTodo = [:]
        updatedTodo["id"] = params.id
        updatedTodo["todoItem"] = params.todoItem
        updatedTodo["dueDate"] = params.dueDate
        def data = toDoItemService.editTodoItem(params)
        render data as JSON
    }

    /**
     * This action invokes a service to fetch to do item
     * */
    def fetchTodo() {
        def data = toDoItemService.fetchTodo(params.id)
        render data as JSON
    }

    /**
     * This action invokes a service to delete to do item
     * */
    def deleteTodo() {
        def data = toDoItemService.deleteTodo(params.id)
        render data
    }

    /**
     * This action invokes a service to sort to do list by due date
     * */
    def sortByDDate() {
        def data = toDoItemService.sortByDdate()
        render data as JSON
    }

    /**
     * This action invokes a service to sort to do list by ceration date
     * */
    def sortByCDate() {
        def data = toDoItemService.sortByCdate()
        render data as JSON
    }

    /**
     * This action invokes a service to search a to do item by text
     * */
    def searchByText() {
        def data = toDoItemService.searchByText(params.text)
        render data as JSON
    }

    /**
     * This action invokes a service to search a to do item by due date
     * */
    def searchByDueDate() {
        def data = toDoItemService.searchByDueDate(params.dueDate)
        render data as JSON
    }

    /**
     * This action invokes a service to search a to do item by due days
     * */
    def searchByDueDays() {
        def data = toDoItemService.searchByDueDays(Integer.parseInt(params.dueDays))
        render data as JSON
    }

    /**
     * This action invokes a service to fetch to do items by status
     * */
    def fetchTodoItemsByStatus() {
        def result = toDoItemService.fetchTodoItemsByStatus(params.status)
        render result as JSON
    }
}
//End: ToDoListController

grails-app/views/include/_common.gsp
<script>
    $(function() {
        registerStatusClickEvent();
        setDatePicker();
        registerFilterClickEvent();
    });

    function registerFilterClickEvent() {
        $("#filter-option-id").on("click", function() {
            var val = $("#filter-option-id").val();
            console.log("Val:" +val);
            //send ajax request for selected value
            displayToDoListByFilter(val);
        });
    }


    function setDatePicker() {
        $('.datepick').each(function(){
            $(this).datepicker();
        });

        $.datepicker.setDefaults({
            dateFormat: 'yy-mm-dd',
            showOn: "both",
            buttonImageOnly: true,
            buttonText: "Calendar"
        });
    }
    function registerDashboardClickEvent() {
        $("#sort-by-creation-date").click(function() {

        });
    }
    function registerStatusClickEvent() {
        $("#todo-table").on('click', '.status-btn', function() {
            console.log(this.id);
            var todoId = this.id.split('-')[1].trim();
            console.log("Id to update: "+todoId);
            updateTodoStatus(todoId);
        });

        $("#todo-table").on('click', '.edit-btn', function() {
            var todoId = this.id.split('-')[1].trim();
            console.log(this.id);
            editTodoItem(todoId);

        });

        $("#todo-table").on('click', '.delete-btn', function() {
            var todoId = this.id.split('-')[1].trim();
            console.log(this.id);
            deleteTodoItem(todoId);
        });
    }

    function hideAll() {
        $("#view-todo-list").hide();
        $("#create-todo-list").hide();
        $("#edit-todo-list").hide();
        $("#search-by-text-div").hide();
        $("#search-by-date-div").hide();
        $("#search-by-days-div").hide();
        $("#search-options-div").hide();
        $("#sort-options-div").hide();
        $("#dashboard-filter").hide();
        $("#status-div").hide();
    }

    function setTableHeaders() {
        $("#view-todo-list").show();
        var htmlString = '<thead>'+
                '<tr>'+
                '<th>'+" Id"+'</th>'+
                '<th>'+" Action Item"+'</th>'+
                '<th>'+" Due Date"+'</th>'+
                '<th>'+" Status"+'</th>'+
                '<th>'+" Creation Date"+'</th>'+
                '</tr>'+
                '</thead>';

        $("#todo-table").html(htmlString);
        $("#todo-table").show();
    }
</script>

grails-app/views/include/_createTodoList.gsp
<script>
    /**
     * Function to create new to do action item
     * */
    function createNewTodoItem() {
        hideAll();
        $("#todo-item-id").val("");
        $("#datepicker1").val("");
        $(".err-msg").hide();
        $("#create-todo-list").show();
    }

    /**
     * Function to add new to do item to db
     * */
    function addToTodoList() {
        if(validateTodoItem($("#todo-item-id").val(), $("#datepicker1").val()) ) {
            var ui_data = {
                "todoItem": $("#todo-item-id").val(),
                "dueDate": $("#datepicker1").val()
            };

            $.ajax({
                url: '<g:createLink controller="toDoList" action="addTodoItem"/>',
                data: JSON.stringify(ui_data),
                type: 'post',
                contentType: 'application/json; charset=utf-8',
                dataType: 'json',
                success: function (data) {
                    if(data.error) {
                        $("#status-div").show();
                        $("#todo-err-msg").html("No records found.").show().delay(4000).fadeOut('slow');
                    } else {
                        getTodoList(0);
                        $("#status-div").show();
                        $("#todo-success-msg").html("New to do item added successfully.").show().delay(4000).fadeOut('slow');
                    }
                },
                error: function() {
                    $("#status-div").show();
                    $("#todo-err-msg").html("Failed to add new to do item").show();
                }
            });
        }
    }

</script>

grails-app/views/include/_deleteTodoList.gsp
<script>
    /**
     * Script to delete to do list
     * */

    function deleteTodoItem(todoId) {
        $.ajax({
            url: '<g:createLink controller="toDoList" action="deleteTodo"/>',
            data: {"id": todoId},
            type: 'post',
            success: function (data) {
                if(data.error) {
                    $("#status-div").show();
                    $("#todo-err-msg").html("No records found.").show().delay(4000).fadeOut('slow');
                } else {
                    getTodoList(0);
                    $("#status-div").show();
                    $("#todo-success-msg").html("To do item deleted successfully.").show().delay(4000).fadeOut('slow');
                }
            },
            error: function() {
                $("#status-div").show();
                $("#todo-err-msg").html("Failed to Delete to do item").show();
            }
        });
    }

</script>

grails-app/views/include/_editTodoList.gsp
<script>
    /**
     * Script to edit to do list
     * */

    function editTodoItem(todoId) {
        hideAll();
        $("#edit-item-id").val("");
        $('#datepicker2').val("");
        $("#edit-todo-list").show();

        $.ajax({
            url: '<g:createLink controller="toDoList" action="fetchTodo"/>',
            data: {"id": todoId},
            type: 'post',
            async: true,
            success: function (data) {
                if(data.error) {
                    $("#status-div").show();
                    $("#todo-err-msg").html("No records found.").show().delay(4000).fadeOut('slow');
                } else {
                    todoItToEdit = todoId;
                    $("#edit-item-id").val(data["todoItem"]);
                    $('#datepicker2').val(data["dueDate"]);
                    $("#edit-to-do").click(function() {
                        updateTodo(todoId)
                    });
                }
            },
            error: function() {
                $("#status-div").show();
                $("#todo-err-msg").html("Failed to fetch Todo item for edit").show();
            }
        });
    }

    function updateTodo(todoItToEdit) {
        if (validateTodoItem($("#edit-item-id").val(), $("#datepicker2").val())) {
            $.ajax({
                url: '<g:createLink controller="toDoList" action="editTodo"/>',
                data: {"id": todoItToEdit, "todoItem": $("#edit-item-id").val(), "dueDate": $("#datepicker2").val()},
                type: 'post',
                async: true,
                success: function (data) {
                    if(data.error) {
                        $("#status-div").show();
                        $("#todo-err-msg").html("No records found.").show().delay(4000).fadeOut('slow');
                    } else {
                        getTodoList(0);
                        $("#status-div").show();
                        $("#todo-success-msg").html("To do item saved successfully.").show().delay(4000).fadeOut('slow');
                    }
                },
                error: function () {
                    $("#status-div").show();
                    $("#todo-err-msg").html("Failed to edit to do item").show();
                }
            });
        }
    }

    /**
     * Script to update status of to do list
     * */

    function updateTodoStatus(todoId) {
        $.ajax({
            url: '<g:createLink controller="toDoList" action="updateStatus"/>',
            data: {"id": todoId},
            type: 'post',
            success: function (data) {
                if(data.error) {
                    $("#status-div").show();
                    $("#todo-err-msg").html("No records found.").show().delay(4000).fadeOut('slow');
                } else {
                    getTodoList(0);
                    $("#status-div").show();
                    $("#todo-success-msg").html("To do item status updated successfully.").show().delay(4000).fadeOut('slow');
                }
            },
            error: function() {
                $("#status-div").show();
                $("#todo-err-msg").html("Failed to update status").show();
            }
        });
    }
</script>

grails-app/views/include/_fetchTodoList.gsp
<script>
    /**
     * Function to fetch whole to do list
     * */

    $(function() {
        getTodoList(0);
    });

    function getTodoList(flag) {
        hideAll();
        if(flag == 1) {
            $("#dashboard-filter").show();
        }
        $("#view-todo-list").show();
        setTableHeaders();
        $.getJSON('<g:createLink controller="toDoList" action="getToDoItems"/>',function(data){
            var rowData = JSON.stringify(data);
            var count = 1;
            if(data.error) {
                $("#status-div").show();
                $("#todo-err-msg").html("No records found.").show().delay(4000).fadeOut('slow');
            } else {
                $.each(data, function(index, rowData) {
                    if(rowData[3] == "Done") {
                        $("#todo-table").append('<tr>' +
                        '<td>'+count+'</td>' +
                        '<td>'+rowData[1]+'</td>' +
                        '<td>'+rowData[2]+'</td>' +
                        '<td>'+rowData[3]+'</td>' +
                        '<td>'+rowData[4]+'</td>' +
                        '<td><button class="completed btn btn-default" id="status-'+rowData[0]+'">'+"Completed"+'</button >' +'</td>' +
                        '<td><button class="edit-btn btn btn-default" id="edit-'+rowData[0]+'">'+"Edit"+'</button></td>' +
                        '<td><button class="delete-btn btn btn-default" id="delete-'+rowData[0]+'">'+"Delete"+'</button></td>' +
                        '</tr>');
                        var idToDisable = "#status-"+rowData[0];
                        $(idToDisable).prop('disabled', true);
                        $("#edit-"+rowData[0]).prop('disabled', true);
                    } else {
                        $("#todo-table").append('<tr>' +
                        '<td>'+count+'</td>' +
                        '<td>'+rowData[1]+'</td>' +
                        '<td>'+rowData[2]+'</td>' +
                        '<td>'+rowData[3]+'</td>' +
                        '<td>'+rowData[4]+'</td>' +
                        '<td><button class="status-btn btn btn-default" id="status-'+rowData[0]+'">'+"Mark as Complete"+'</button >' +'</td>' +
                        '<td><button class="edit-btn btn btn-default" id="edit-'+rowData[0]+'">'+"Edit"+'</button>' +'</td>' +
                        '<td><button class="delete-btn btn btn-default" id="delete-'+rowData[0]+'">'+"Delete"+'</button></td>' +
                        '</tr>');

                        var idToDisable = "#status-"+rowData[0];
                        $(idToDisable).prop('disabled', false);
                        $("#edit-"+rowData[0]).prop('disabled', false);
                    }
                    count++;
                });
            }
        });
    }

    /**
     * Function to filter to do list by status
     * */

    //Filter options like All, Pending, Completed
    function dispalyFilterOptions() {
        getTodoList(1);
        $("#filter-option-id").val("All");
        $("#dashboard-filter").show();
        $("#view-todo-list").show();
    }

    function displayToDoListByFilter(val) {
        $("#dashboard-filter").show();
        if(val == "All") {
            getTodoList(1);
        } else {
            showTodoItemsByStatus(val);
        }
    }

    /**
     * Function to display to do list by status
     * */
    function showTodoItemsByStatus(val) {
        hideAll();
        $("#dashboard-filter").show();
        $("#view-todo-list").show();
        $("#todo-table").show();
        setTableHeaders();
        var count = 1;
        $.ajax({
            url: '<g:createLink controller="toDoList" action="fetchTodoItemsByStatus"/>',
            data: {"status": val},
            type: 'get',
            success: function (data) {
                if(data.error) {
                    $("#status-div").show();
                    $("#todo-err-msg").html("No records found.").show().delay(4000).fadeOut('slow');
                } else {
                    $.each(data, function(index, rowData) {
                        if(rowData[3] == "Done") {
                            $("#todo-table").append('<tr>' +
                            '<td>'+count+'</td>' +
                            '<td>'+rowData[1]+'</td>' +
                            '<td>'+rowData[2]+'</td>' +
                            '<td>'+rowData[3]+'</td>' +
                            '<td>'+rowData[4]+'</td>' +
                            '<td><button class="status-btn btn btn-default" id="status-'+rowData[0]+'">'+"Completed"+'</button ></td>' +
                            '<td><button class="edit-btn btn btn-default" id="edit-'+rowData[0]+'">'+"Edit"+'</button></td>' +
                            '<td><button class="delete-btn btn btn-default" id="delete-'+rowData[0]+'">'+"Delete"+'</button></td>' +
                            '</tr>');

                            var idToDisable = "#status-"+rowData[0];
                            $(idToDisable).prop('disabled', true);
                            $("#edit-"+rowData[0]).prop('disabled', true);
                        } else {
                            $("#todo-table").append('<tr>' +
                            '<td>'+count+'</td>' +
                            '<td>'+rowData[1]+'</td>' +
                            '<td>'+rowData[2]+'</td>' +
                            '<td>'+rowData[3]+'</td>' +
                            '<td>'+rowData[4]+'</td>' +
                            '<td><button class="status-btn btn btn-default" id="status-'+rowData[0]+'">'+"Mark as Complete"+'</button ></td>' +
                            '<td><button class="edit-btn btn btn-default" id="edit-'+rowData[0]+'">'+"Edit"+'</button></td>' +
                            '<td><button class="delete-btn btn btn-default" id="delete-'+rowData[0]+'">'+"Delete"+'</button></td>' +
                            '</tr>');
                            var idToDisable = "#status-"+rowData[0];
                            $(idToDisable).prop('disabled', false);
                            $("#edit-"+rowData[0]).prop('disabled', false);
                        }
                        count++;
                    });
                }
            },
            error: function() {
                $("#status-div").show();
                $("#todo-err-msg").html("Failed to filter by Status "+val).show();
            }
        });
    }
</script>

grails-app/views/include/_searchTodoList.gsp
<script>
    /**
     * Script to search to do list by text, due date and due days
     * */

    function displaySearchOptions() {
        getTodoList(0);
        $("#search-options-div").show();
    }

    function showSearchByText() {
        hideAll();
        $("#search-options-div").show();
        $("#search-by-text-div").show();
        $("#search-by-text").val("");
        $("#search-by-text").focus();
    }

    function showSearchByDate() {
        hideAll();
        $("#search-by-date-div").show();
        $("#search-options-div").show();
        $("#datepicker3").val("");
        $("#datepicker3").focus();
    }

    function showSearchByDays() {
        hideAll();
        $("#search-by-days-div").show();
        $("#search-options-div").show();
        $("#search-days-id").val("");
        $("#search-days-id").focus();
    }

    function searchByText() {
        hideAll();
        $("#search-options-div").show();
        $("#view-todo-list").show();
        $("#todo-table").show();
        setTableHeaders();
        var count = 1;
        $.ajax({
            url: '<g:createLink controller="toDoList" action="searchByText"/>',
            data: {"text": $("#search-by-text").val()},
            type: 'post',
            success: function (data) {
                if(data.error) {
                    $("#status-div").show();
                    $("#todo-err-msg").html("No records found.").show().delay(4000).fadeOut('slow');
                } else {
                    $.each(data, function(index, rowData) {
                        if(rowData[3] == "Done") {
                            $("#todo-table").append('<tr>' +
                            '<td>'+count+'</td>' +
                            '<td>'+rowData[1]+'</td>' +
                            '<td>'+rowData[2]+'</td>' +
                            '<td>'+rowData[3]+'</td>' +
                            '<td>'+rowData[4]+'</td>' +
                            '<td><button class="status-btn btn btn-default" id="status-'+rowData[0]+'">'+"Completed"+'</button ></td>' +
                            '<td><button class="edit-btn btn btn-default" id="edit-'+rowData[0]+'">'+"Edit"+'</button></td>' +
                            '<td><button class="delete-btn btn btn-default" id="delete-'+rowData[0]+'">'+"Delete"+'</button></td>' +
                            '</tr>');

                            var idToDisable = "#status-"+rowData[0];
                            $(idToDisable).prop('disabled', true);
                            $("#edit-"+rowData[0]).prop('disabled', true);
                        } else {
                            $("#todo-table").append('<tr>' +
                            '<td>'+count+'</td>' +
                            '<td>'+rowData[1]+'</td>' +
                            '<td>'+rowData[2]+'</td>' +
                            '<td>'+rowData[3]+'</td>' +
                            '<td>'+rowData[4]+'</td>' +
                            '<td><button class="status-btn btn btn-default" id="status-'+rowData[0]+'">'+"Mark as Complete"+'</button ></td>' +
                            '<td><button class="edit-btn btn btn-default" id="edit-'+rowData[0]+'">'+"Edit"+'</button></td>' +
                            '<td><button class="delete-btn btn btn-default" id="delete-'+rowData[0]+'">'+"Delete"+'</button></td>' +
                            '</tr>');

                            var idToDisable = "#status-"+rowData[0];
                            $(idToDisable).prop('disabled', false);
                            $("#edit-"+rowData[0]).prop('disabled', false);
                        }
                        count++;
                    });
                }
            },
            error: function() {
                $("#status-div").show();
                $("#todo-err-msg").html("Failed to search by Text").show();
            }
        });
    }

    function searchByDate() {
        hideAll();
        $("#search-options-div").show();
        $("#view-todo-list").show();
        $("#todo-table").show();
        setTableHeaders();
        var count = 1;
        $.ajax({
            url: '<g:createLink controller="toDoList" action="searchByDueDate"/>',
            data: {"dueDate": $("#datepicker3").val()}, //use number of days
            type: 'post',
            success: function (data) {
                if(data.error) {
                    $("#status-div").show();
                    $("#todo-err-msg").html("No records found.").show().delay(4000).fadeOut('slow');
                } else {
                    $.each(data, function(index, rowData) {
                        if(rowData[3] == "Done") {
                            $("#todo-table").append('<tr>' +
                            '<td>'+count+'</td>' +
                            '<td>'+rowData[1]+'</td>' +
                            '<td>'+rowData[2]+'</td>' +
                            '<td>'+rowData[3]+'</td>' +
                            '<td>'+rowData[4]+'</td>' +
                            '<td><button class="status-btn btn btn-default" id="status-'+rowData[0]+'">'+"Completed"+'</button ></td>' +
                            '<td><button class="edit-btn btn btn-default" id="edit-'+rowData[0]+'">'+"Edit"+'</button></td>' +
                            '<td><button class="delete-btn btn btn-default" id="delete-'+rowData[0]+'">'+"Delete"+'</button></td>' +
                            '</tr>');

                            var idToDisable = "#status-"+rowData[0];
                            $(idToDisable).prop('disabled', true);
                            $("#edit-"+rowData[0]).prop('disabled', true);
                        } else {
                            $("#todo-table").append('<tr>' +
                            '<td>'+count+'</td>' +
                            '<td>'+rowData[1]+'</td>' +
                            '<td>'+rowData[2]+'</td>' +
                            '<td>'+rowData[3]+'</td>' +
                            '<td>'+rowData[4]+'</td>' +
                            '<td><button class="status-btn btn btn-default" id="status-'+rowData[0]+'">'+"Mark as Complete"+'</button ></td>' +
                            '<td><button class="edit-btn btn btn-default" id="edit-'+rowData[0]+'">'+"Edit"+'</button></td>' +
                            '<td><button class="delete-btn btn btn-default" id="delete-'+rowData[0]+'">'+"Delete"+'</button></td>' +
                            '</tr>');
                            var idToDisable = "#status-"+rowData[0];
                            $(idToDisable).prop('disabled', false);
                            $("#edit-"+rowData[0]).prop('disabled', false);
                        }
                        count++;
                    });
                }
            },
            error: function() {
                $("#status-div").show();
                $("#todo-err-msg").html("Failed to search by Due Dates").show();
            }
        });
    }

    function searchByDueDays() {
        hideAll();
        $("#search-options-div").show();
        $("#view-todo-list").show();
        $("#todo-table").show();
        setTableHeaders();
        var count = 1;
        $.ajax({
            url: '<g:createLink controller="toDoList" action="searchByDueDays"/>',
            data: {"dueDays": $("#search-days-id").val()}, //use number of days
            type: 'get',
            success: function (data) {
                if(data.error) {
                    $("#status-div").show();
                    $("#todo-err-msg").html("No records found.").show().delay(4000).fadeOut('slow');
                } else {
                    $.each(data, function(index, rowData) {
                        if(rowData[3] == "Done") {
                            $("#todo-table").append('<tr>' +
                            '<td>'+count+'</td>' +
                            '<td>'+rowData[1]+'</td>' +
                            '<td>'+rowData[2]+'</td>' +
                            '<td>'+rowData[3]+'</td>' +
                            '<td>'+rowData[4]+'</td>' +
                            '<td><button class="status-btn btn btn-default" id="status-'+rowData[0]+'">'+"Completed"+'</button ></td>' +
                            '<td><button class="edit-btn btn btn-default" id="edit-'+rowData[0]+'">'+"Edit"+'</button></td>' +
                            '<td><button class="delete-btn btn btn-default" id="delete-'+rowData[0]+'">'+"Delete"+'</button></td>' +
                            '</tr>');

                            var idToDisable = "#status-"+rowData[0];
                            $(idToDisable).prop('disabled', true);
                            $("#edit-"+rowData[0]).prop('disabled', true);
                        } else {
                            $("#todo-table").append('<tr>' +
                            '<td>'+count+'</td>' +
                            '<td>'+rowData[1]+'</td>' +
                            '<td>'+rowData[2]+'</td>' +
                            '<td>'+rowData[3]+'</td>' +
                            '<td>'+rowData[4]+'</td>' +
                            '<td><button class="status-btn btn btn-default" id="status-'+rowData[0]+'">'+"Mark as Complete"+'</button ></td>' +
                            '<td><button class="edit-btn btn btn-default" id="edit-'+rowData[0]+'">'+"Edit"+'</button></td>' +
                            '<td><button class="delete-btn btn btn-default" id="delete-'+rowData[0]+'">'+"Delete"+'</button></td>' +
                            '</tr>');
                            var idToDisable = "#status-"+rowData[0];
                            $(idToDisable).prop('disabled', false);
                            $("#edit-"+rowData[0]).prop('disabled', false);
                        }
                        count++;
                    });
                }
            },
            error: function() {
                $("#status-div").show();
                $("#todo-err-msg").html("Failed to search by Due Days").show();
            }
        });
    }
</script>

grails-app/views/include/_validation.gsp
<script>

    function validateTodoItem(todoAction, dueDate) {
        $("#todo-err-msg").hide();
        $("#status-div").show();
        console.log("Validating new todo item");
        var isTodoItemValid = true;
        var isDueDateValid = true;

        var date = new Date();
        var year = date.getFullYear();
        var month = date.getMonth()+1;
        var day = date.getDate();
        var today = year +''+month +''+ day;
        dueDate = dueDate.toString();

        //Todo: Check for replaceAll
        dueDate = dueDate.replace('-', '');
        dueDate = dueDate.replace('-', '');


        if( (todoAction == "" || todoAction == null) && (dueDate == "" || dueDate == null ))  {
            console.log("item1");
            $("#todo-err-msg").html("Please add To Do Action Item and a Due Date.").show();
            isTodoItemValid = false;
        } else if( (todoAction == "" || todoAction == null) && (parseInt(dueDate) <= parseInt(today)))  {
            console.log("item1");
            $("#todo-err-msg").html("Please add To Do Action Item and a valid Due Date.").show();
            isTodoItemValid = false;
        } else if(parseInt(dueDate) <= parseInt(today)){
            isDueDateValid = false;
            $("#todo-err-msg").html("Please select valid Due Date.").show();
            console.log("please select valid due date");
        } else if(dueDate == "" || dueDate == null ) {
            console.log("item2");
            $("#todo-err-msg").html("Please select Due Date").show();
            isDueDateValid = false;
        } else if(todoAction == "" || todoAction == null) {
            isDueDateValid = false;
            $("#todo-err-msg").html("Please add To do Action Item").show();
            console.log("Please add To do Action Item");
        }

        console.log(isTodoItemValid && isDueDateValid);
        return isTodoItemValid && isDueDateValid
    }
</script>

grails-app/views/layouts/main.gsp
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"><!--<![endif]-->
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<title><g:layoutTitle default="Grails"/></title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="shortcut icon" href="${assetPath(src: 'favicon.ico')}" type="image/x-icon">
		<link rel="apple-touch-icon" href="${assetPath(src: 'apple-touch-icon.png')}">
		<link rel="apple-touch-icon" sizes="114x114" href="${assetPath(src: 'apple-touch-icon-retina.png')}">
  		<asset:stylesheet src="application.css"/>
		<asset:javascript src="application.js"/>
		<g:layoutHead/>
	</head>
	<body>
		<div id="grailsLogo" role="banner"><a href="http://grails.org"><asset:image src="grails_logo.png" alt="Grails"/></a></div>
		<g:layoutBody/>
		<div class="footer" role="contentinfo"></div>
		<div id="spinner" class="spinner" style="display:none;"><g:message code="spinner.alt" default="Loading&hellip;"/></div>
	</body>
</html>